import Link from 'next/link';

export default function Bestie() {
    return (
        <div>
            Hi Debu,<br/>
            I hope you're doing good. There is sooo much I wanna talk about. I'm sorry about leaving you, I didnt mean to hurt you, and im really sorry about that. Leaving you literally broke me and drove me insane. I thought I was doing fine but suddenly I got soo miserable and depressed and panicy. But we can talk all about it when we meet. <br/>
            This semester has been very different from the ones before. I was mostly just trying to find myself and stay content in my own company. I started working out, finishing my homework on time, working on projects, applying for internships, etc but thats boring, so lemme tell you about some crazy things that happened so far this sem. One day I was making pasta for 3 people and I pulled a Debu. I spilled the entire pan full of pasta in the sink while draining. I got sooo upset for both wasting pasta and the time to boil it all again and the worst part is that it clogged my kitchen sink for 3 days and everything started leaking and it was a whole mess. Big oof. Apparently I make a flavorful spicy pasta. <br/><br/>
            The first party I attended this semester was a really lit party with so many drunk people and good dancers and hot chicks. The problem was that I was in campus most of the day and then I went to Tanay's place to do some homework so we got late and then he procrastinated taking a bath and stuff so it got even late and i wasnt able to go back home to change my clothes before the party. That day I was wearing a really old T-Shirt and my boobs were really really prominent. And I had my bag with me. So with all this I went to the party and literally everyone was staring at me and laughing and I wasnt able to dance cuz im not a dancer so i was just sitting in a corner with a drink and atleast 4 couples got together by making fun of me and having that as their common talking point. They were literally laughing at my face and it was such a bad day. I was the dude with the boobs who brought a bag to a party lmao. <br/><br/>
            Do you remember my Audible Maps for ASU project? I was working on that this sem. It went horribly cuz Google doesnt allow making a navigation app using Google Maps API. So we had to switch to Mapbox and start from scratch. This ruined my first presentaion of the app. That presentation got to my nerves and I decided to do something about it. I signed up for a pitch competition and set myself a deadline to finish it before that. I worked day and night and I got to work, but the day of the pitch presentation the code broke and it had some weird errors that i just could not fix. So I wrote an email saying that i dont wanna present anymore. But they motivated me to try and they told me that I didnt have to show the final product, they just wanted to see my buisness plan. So I asked Sam to help and she made a presentation for me using some AI. I went late for it but i reached exactly when I had to present. My presentation was okish but my answers to their questions were very prompt. After everyone was done, I they told us that they needed some time to compile the results and went to another room for that. In that time, I knew i wasnt gonna win so I stole some of their pizza and headed out to eat with friends lmao. <br/><br/>
            The next day I was feeling lazy going to class and I had to cuz of the attendance quiz which is locked behind a password that they only tell in class. Dude I got it right on the first try. Can you believe it? The password was geometric. Right after that, our entire got an email saying that we won the competition ($1,000 in funding) and wanted us to write something for their social media post. I still cant believe that we won that shit.<br/><br/>
            This was my worst birthday yet prolly. I cried the entire morning in the campus infront of everyone. I just couldnt stop it. I spent like $200 on a dead party that no one came to. And all I got as gifts were 7 gm of weed and a bottle of champagne. The tiny handful people that i didnt know who cam eto the party smoked most of it and I only got to drink like 2 sips of the champagne. I felt soo horrible. Karma served me right. <br/><br/>
            I wanna cut off everything with Krish. He is an asshole who is adding 0 value to my life. He's a shit person, shittier boyfriend and the shittiest friend. Fuck him. He's just an egoistic rich brat. I honestly dont know why Sam hasnt broken up already. If I treated you or my friends like him then forget everything I said and close this because I dont deserve to live. His mom would be the only one happy to reunite with him. He's literally a burden on everthing and everyone and absolutely no one cares if he dies. <br/><br/>

            <div>
                Other things you might be interested in: 
                <li><Link href="/debu/catpics">Cat pics</Link></li>
                <li><Link href="/debu/thingsiwannado">Things I wanna do with you</Link></li>
                <li><Link href="/debu/bestie">Bestie Stuff</Link></li>
                <li><Link href="/debu/mean">Mean things I wanna say</Link></li>
                <li><Link href="/debu/nextsteps">Next Steps</Link></li>
            </div>
        </div>
    )
}