import Link from 'next/link';

export default function Debu() {
    return (
        <div className='text-center m-12 text-lg'>
            My code predicter software thought Im gonna write about Debug. 😂<br/>
            I'm writing this with a calm mind. I miss you a lot. You have no idea how much it kills me know that I left you in pieces. I'm sorry i did that but I just had to. Im sorry it had to be this way but please hear me out. This is my honest perspective, took me a lotta courage to say this and ik it doesnt mean anything cuz so much time has passed you might think that im making it up but believe me im not. I just needed a lot of time to think about it. <br/>
            Im sorry I did this to you. I wasn't happy in our relationship. Im sorry to say all these things. I never did before because I didnt want to sound mean but it fucked me over. <br/><br/>
            I wasnt happy because you wanted me to do things that didnt make sense to me like telling you when I'd come back from a friend's place before leaving so that you know when to call me. It did not make sense to me, im sorry, but ive realized that I wasted my entire second year and Im the only one to blame. I forgot my priorities and I shouldve managed my time better. You were right I shouldve set a time for myself to come back at. Instead I would forget to keep track of time or even worse call my friends in my room. But I had my reason (not a good one). Im sorry but I really wanted to smoke weed and game. Gaming was my dream and weed just made living it better. It was my dream for such a long time, the exact setup i have, the exact monitor, soundbar and pc parts that Ive always wanted for sooo many years and it was a huge mistake i know but i really liked doing it. It was also my dream to date you and I was already doing it for a year and the emotional and getting to know you things from 4 years before it. Our honeymoon period was over and I wanted to live my life with the people I had here too. Our convos had died and if they hadnt, they were surly not how they used to be. When we would talk about random things in a very random way and take the conversation from a minecraft playthrough to a gay designer to a technique of cooking lamb in a certain way to some very hypothtical situation where you have to choose between two equal stakes scenarios and we would always end up learning something new about each other. However in the relationship we only talked about hows you, how was your day and do you have any plans? <br/><br/>
            But guess what, im the dumbest person Ive ever seen. Gaming made me a lazy couch potato and weed made me slower and lose track of time and people/things that mattered. I shouldnt have bought the PC cuz im still in credit debt. I lost the love of my life. I shouldve worked hard to chase my dream and earned the PC myself. Just like the PC, you were my dream too but I've always wanted to chase you. I wanted to go on dates with you, street shopping, random cute places, do dumb weird shit, but you never wanted to date me, so i never took you out. I fucking lost my mind when you said you wanted to date me. Because I wanted to too. It was going good but it didnt feel real because I started to think that you're only locking me down cuz you had no one else and you didnt wanna lose me. I felt like a backup and you redeemed me at the worst time (for me). I knew you didnt have your school friends to talk to, you didnt wanna get too attached to the people in NIFT, idk bout your other friends, and I, the person who cared for you the most and loved you unconditionally also reduced talking to you cuz I was also in college living my life here plus the time diff. I was never romantic, I never made you feel loved in the way you wanted from a boyfriend before. And I couldnt figure it out because I needed to physically be there with you to understand that. But I didnt say anything because I knew exactly how horrible it feels when your friends move on and people younger than you started college before you and your younger sibling had a better college prospect. I thought you'd talk about that just like youve talked about everything else. But you never did. And I understand why and morever you were happy now that we were dating, and you didnt feel most of that anymore and im sure you had your reasons. <br/>
            But then you said that you didnt wanna count the 4 years and we were gonna start things like new and I honestly didnt know what it meant. I mean if you take the 4 years out of the equation, we had nothing. We have nothing in common, almost no matching interests and completely different time zones. But we loved each other. Our love was about being there for each other, trusting each other with everything and making us better for each other and selves. But you didnt talk about it. You didnt want me to talk about the relationship before me coming to India and after that you didnt want me to talk about it until August. I wanted to say that I'll be there for you when you need me and if we talk everyday then we'll check up, vent out, and motivate each other to do better during the long distance because of time diff probs and I wanted to spend time with people here, and be your boyfriend when im physically with you. I mean you were permanent and always had been. I knew you needed my support the most till you started college and both us knew our lives wouldve been better if we were in college. Honestly if you'd told me about those feelings instead of dating, I wouldve just told you to wait till college, your life will be better and I would always be there for you. But you were sooo deep in love with me that I didnt have the courage to say that I wanted to talk less in college. I mean that wouldve also meant that I wouldnt be able to look after you all the time and I didnt wanna imply that. So I did nothing. <br/>
            But you still needed me all the time. I know you said that you only need 5 mins of my attention but that not true and we did talk for hours upon hours but it wasnt good enough. I know its my fault I shouldve managed my time better but I didnt like you telling me to tell you when im gonna be back, or to not play valo, give you attention when thats all I did in the past years. <br/><br/>
            I said it before that I needed to actually miss you to miss you. That just meant that i needed a real break but i was never good at communicating. I know i wasnt explicit with that but i had forgotton how to talk about my feelings with you. I was suffering here. I didnt like living here, i didnt like my friends, i didnt like myself and I didnt like you not letting me feel good about playing Valo. I was crying so much everyday and i wanted to die. But you didnt want me to talk about me dying and its just no the same on call as it wouldve been if i was actually with you. I thought youd know how to get me talking about my feelings but you didnt and I stopped sharing bad things wiht you. But I had nothing good going on. If i had a job if i wanted to make more friends i wouldve had a happier life of my own but i was never able to do that cuz in the back of my mind i was always worried about how i should put more efforts in our relationship. And i honestly didnt want to cuz i had done that for 4 years it was time for me to enjoy my life and the things i wanted to to but it just hurt to know that you wanted to forget about it and start something new. I was never that romantic with you before and the long distance just never let me. <br/><br/>
            Now about July. I didnt wanna do it. I didnt wana promise you a romantic july. You really wanted me to and I had fucked up so much that i thought this would be a test for me and if i failed then i just didnt deserve you. And I failed. I failed because my parents didnt like me hanging out with you, I stopped loving hanging out with you and we were broke. I really tried, i got that 30 mins trailler walla idea, I wanted to go to an art museuem or a book fair or an observatory. But there were no events or exhibitions going on and my dad didnt allow me to drive in Delhi. I knew I wasnt gonna enjoy arcade because I knew the games were gonna be shit, we wouldnt be able to do much and I was just losing money. idk why i was thinking like that when I shouldve been happy to hang out with you. But you also need to realise that there are other poeple I wanted to spend time with like my parents, my bachpan ke friends and my nani who i drove to labs for her tests almost everyday to either get it done or get the reports. And I was sad to have been made to promise this romantic July. I really wasnt prepared for it and ik i shoulve, i had plenty of time but i just stayed lazy. You didn't even do anything to plan or make me realize that im still slacking off. I felt helpless when you left it all on me. Ik I shouldnt have I couldve asked for help from Noddy or Sam but I could only ever imagine asking that advice from you and I couldnt do that. But im glad cuz I never wouldve realized how much I was hurting you and I never wouldve tried to get better. I could not see you cry in the car that day I hated myself so much for putting you through it. So I broke up. I needed a break to realize why i loved you. I was trying really hard to love you while forgetting those 4 years and I just couldnt. <br/><br/>
            You asked me in the relationship why I loved you and I had nothing to say. I didnt know why I loved you or why we were in our relationship. I needed some time alone to figure it out. I love you because you were there for me during really hard times. I loved you because you made me feel alive. You made me feel like im something worth living for. But i wasnt living for me. I was only living my life because I was born. I hated being alive, but you saw something in me. Being with you always gave me courage to try something new and I knew you'd always have my back and cheer me up. But it was all only possible if I was doing somehting. When we were in a relationship I wasnt doing anything with my life. I needed to fall in love with you again and i needed to fall in love with my self. I had to break up because I was treating you like shit and i was turning into a monster. You were never gonna leave me and it wouldve made us sadder. We wouldve been in a really really bad relationship. The breakup helped me realize my love for you and programming. It made me finally realize that i need to get good and life is worth living. Its worth putting all the effort in the relationship and in my personal career stuff. I never gave my 100% into anything but ive achieved things this semester i never imagined I could. You've made me a believer. <br/><br/>
            Im sorry our long distance failed. Im sorry I was never good for you. But I know I can be. Just give me one chance to prove it. I am not capable of trusting another human again. I am never gonna be able to talk about my feelings. I dont think anyone is good enough. Im sorry I fucked up in the past but you know I had never failed you before and my love only grows stronger. It sucks that i cant do anything about it. I really wnated to come meet you in Jaipur and tell you all this but my parents didnt let me. I wanted to go to Dehradun more to just be peaceful by myself but they didnt let me go there too. The needed my help with an event they were organising for like 250 people + audience and I honestly liked helping them with that. Cuz i knew i could do it and I needed to get good and It made me fall in love with programming again cuz i made a program to generate custom tambola tickets and it was fun coding that. <br/><br/>
            All I want to do right now is to show you how much I actually love you but I cant. i want to give you a romantic time but its too late now. That hug in Rishikesh wasnt a scam. It made me fall in love with you even more. But idk why I didnt do anything. I was really enjoying spedning time with Garv and talking about the PS5. I know I couldve done all of these things while also not ignoring you and i know if i communicated you wouldve let me do everything and youd undertsnad. But I didnt know how to. I didnt know how to take a stand. I was indecisive. Im sorry i was just really immature and I pushed you away for absolutely no reason. <br/><br/>


            Devyani, I have realized. I was a lazy ass person who was so happy to have you as his girlfriend that I thought I had won everything and I didnt need to do naything. I wanted to keep on playing games and you to earn money for me and fuel my addiction. But i was wrong. I shouldve been better. I started losing my personality and stopped making you happy. But this relationship was stressful cuz i didnt know how to handle a relationship let alone commitment. I was overwhelmed with your love and didnt know how to make you happy and i didnt like how many restrictions it felt like i had. But Ive realized that it was only to make our life better, and I was still stuck up on my life. Ive realized that gaming is a shitty thing and i need to make a name for myself. I dont expect you to understand this but I realized that i was never happy because I was fat and i didnt like to be seen in public with you because youre the most beautiful person in this world and i am sooo fucking ugly and fat like a pig. I didnt like it. Being fat made me lethargic and underconfident in everything. I became lazier and my body got stiffer and I my body pained in different places. I always have obesity problems in my mind and I still never did anything about it. I don't like talking about it because my parents always warned me about it and tried really hard to get me to work out, but I'd always end up eating way more than I could stuff in, almost everyday in 10th-12th. I have 0 core strength and I literally need support to even stand. Thats why I usually pace around instead of standing and my ass feels weird to sit so I sometimes don't. Ik its my own dumb decisions but im trying really hard to fix it. I only realized all this because im taking care of myself and I feel so much better. My body doesnt pain anymore and I'm thinking clearer. Ive given up on gaming and im only smoking weed because im miserable sober and I cant stop thinking about you and the way I made you feel during the relationship and even worse after it. I know it mustve been hard to forget the feelings for me and live your life. But the thought of you having a bad boyfriend streak for so long (me included), I just cant imagine the thought of anyone else putting you through it all again. I know you have a way better taste in boys now but I want to be the one to put an end to it. I want to treat you like you deserve. I want to get you surprises regularly. I wanna be by your side and give you confidence to do anything you want to do. I know you dont need me for that but I want to make you mine. I dont want to be shy to show you off. I want to tell the world the you're the love of my life and I'll make all the sacrifices for you. I'm not gonna make you wait if I have people over because youre better than everyone else and you deserve the topmost priority. I want this to be OUR life and Im gonna treat you like a part of me like ive always felt in my heart. I am finally ready for commitment.<br/><br/>

            I didnt love myself which is something youve told me to do but Devyani it comes from within. Literally everyone tried telling me that, everyone tried motivating me to fix it. But that spark of passion only comes from within. Im sorry I didnt know what heartbreak felt like. I didnt know what actually losing you felt like. Being apart from you made realize everything. Its what drives me to be better and to keep my shit together. I don't want to lose you. I cant let the world treat you poorly every again. You're too precious to me.<br/>
            
            
        
            I still wanna make breakfast in bed for you, i wanna learn to professionally massage your back. I wanna be your eyes and ears. I wanna grab you by your waist, look in your eyes and tell you that I love you. I wanna make you laugh and lick your eyeballs when you cry. I can see you getting angry everytime I say that I was stressed and even more when I say it didnt feel real. But it really didnt and it was probably because I knew how much better it wouldve been if we were not in a long distance or atleast if the distance as shorter. I know it wouldnt have gone like this if we dated during school, but you wanted different kind of guys then. I wanted us to be a power couple in our relationship. I wanted you to scold me if I didnt complete my assignment or didnt go to the gym but you didnt. I was lost in our relationship and I didnt know what to do about it. I never had my own opinions or a stand for myself. I didnt know how relationships go and what to expect. The truth is that I was fat and lazy and I blamed you for my short-comings. Its a very monster thing to do and thats why I broke up, I will never do it again because I've realized that I need to grow the fuck up. You know Im not capable of mistreating you again.<br/>
            Im sorry for everything and im living my worst nightmare. I want to be good for you so please let me. I want to take off the burden of planning and putting efforts from you and do these things myself, perfectly. <br/>I wanna be on your left side the right way.<br/><br/>

            <div>
                Other things you might be interested in: 
                <li><Link href="/debu/catpics">Cat pics</Link></li>
                <li><Link href="/debu/thingsiwannado">Things I wanna do with you</Link></li>
                <li><Link href="/debu/bestie">Bestie Stuff</Link></li>
                <li><Link href="/debu/mean">Mean things I wanna say</Link></li>
                <li><Link href="/debu/nextsteps">Next Steps</Link></li>
            </div>
        </div>
    )
}